packages:
  - 'playground'
  - 'docs'
  # we exclude Nuxt because its dep resolution causes weird problems
  - 'examples/with-express'
  - 'examples/with-nextjs'
  - 'examples/with-nextjs-api'
  - 'examples/with-sveltekit'
  - 'examples/with-vue-3'
