import { SourceType } from './types'

export const NO_SOURCE: SourceType = { filePath: 'unknown', lineNumber: -1 }

export const FLYTRAP_UNSERIALIZABLE_VALUE = 'FLYTRAP_UNSERIALIZABLE_VALUE'
export const FLYTRAP_FUNCTION = 'FLYTRAP_FUNCTION'
export const FLYTRAP_DOM_EVENT = 'FLYTRAP_DOM_EVENT'
export const FLYTRAP_CIRCULAR = 'FLYTRAP_CIRCULAR'

export const FLYTRAP_REPLACE_VALUES = [
	FLYTRAP_UNSERIALIZABLE_VALUE,
	FLYTRAP_FUNCTION,
	FLYTRAP_DOM_EVENT,
	FLYTRAP_CIRCULAR
]
